# Generated by Django 5.0 on 2024-02-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_body",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
