# Generated by Django 5.0 on 2024-02-16 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_commentreply_reply_to"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommentReply",
        ),
    ]
