# Generated by Django 5.0 on 2024-02-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user_account", "0002_alter_customuser_email_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["username"], name="user_accoun_usernam_ac9cfb_idx"
            ),
        ),
    ]
